openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
  description: A simple Task API for managing tasks
paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve a list of all tasks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      description: Add a new task to the list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
  /tasks/{id}:
    get:
      summary: Get a single task by ID
      description: Retrieve a specific task using its unique identifier
      parameters:
        - name: id
          in: path
          required: true
          description: Numeric ID of the task to retrieve
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Task found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Buy groceries
        completed:
          type: boolean
          example: false
      required:
        - id
        - title
        - completed
    TaskInput:
      type: object
      properties:
        title:
          type: string
          example: Buy groceries
        completed:
          type: boolean
          example: false
      required:
        - title
    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: Validation failed
        details:
          type: array
          items:
            type: string
          example:
            - ID must be a number
      required:
        - error
        - details
    NotFoundError:
      type: object
      properties:
        error:
          type: string
          example: Task not found
      required:
        - error
