openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
  description: Simple Task Management API

servers:
  - url: https://your-task-api.onrender.com
    description: Production Server
  - url: http://localhost:3000
    description: Local Development

paths:
  /tasks:
    $ref: './paths/tasks.yaml'
  /tasks/{id}:
    $ref: './paths/tasks-id.yaml'

components:
  schemas:
    Task:
      $ref: './components/schemas/Task.yaml'
    ValidationError:
      $ref: './components/schemas/ValidationError.yaml'
    NotFoundError:
      $ref: './components/schemas/NotFoundError.yaml'
